[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Highlights = "eafb193a-b7ab-5a9e-9068-77385905fa72"
Typst_jll = "eb4b1da6-20f6-5c66-9826-fdb8ad410d0e"
tree_sitter_bash_jll = "7332bcdc-bd2a-5999-b4fe-680b85f40771"
tree_sitter_go_jll = "beecb120-e197-59fa-b79c-0316d51c9920"
tree_sitter_javascript_jll = "ca45b743-11fc-5578-b74a-7528860c0bda"
tree_sitter_julia_jll = "52be201e-a5e9-5cfe-8bf2-2dc4b062171c"
tree_sitter_python_jll = "88db161d-10c7-51e6-aa56-e32ecf738a46"
tree_sitter_r_jll = "fc627389-31b9-5eeb-8794-6fbf305d88d7"
tree_sitter_rust_jll = "b2197e8e-fe20-5781-846b-d7979e3cddf2"

[compat]
Documenter = "1"
